# Change these first
owner: NoteSwiper # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: noteswiper.mydns.jp
    url: https://noteswiper.mydns.jp
  - name: noteswiper.github.io
    url: https://noteswiper.github.io

assignees:
  - NoteSwiper

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "NoteSwiper's website upptime checker"
  introMessage: "All of 'f5.si' domains are shown as down for unknown reason. Any 'f5.si' domains are accesible, but it's hosted with DDNS, may blocked by some router or firewalls."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
