# Change these first
owner: NoteSwiper # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Website (MyDNS)
    url: https://noteswiper.mydns.jp
    ipv6: true
    slug: noteswiper-mydns
    maxResponseTime: 10000
    delay: 10000
    expectedStatusCodes:
      - 200
      - 404
      - 403
      - 502
      - 503
  - name: API (MyDNS)
    url: https://api.noteswiper.mydns.jp
    ipv6: true
    maxResponseTime: 10000
    delay: 10000
    slug: api-noteswiper
    expectedStatusCodes:
      - 200
      - 404
      - 403
      - 502
      - 503
  - name: Website IPv4 (MyDNS)
    url: https://noteswiper.mydns.jp
    maxResponseTime: 10000
    delay: 10000
    expectedStatusCodes:
      - 200
      - 404
      - 403
      - 502
      - 503
    slug: ipv4swiper
  - name: Website (GitHub Pages)
    url: https://noteswiper.github.io
    delay: 12000
    slug: gitswiper

assignees:
  - NoteSwiper

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: dark
  introTitle: "NoteSwiper's website upptime checker"
  introMessage: "All of 'mydns.jp' and 'f5.si' domains are shown as down for unknown reason. Any 'mydns.jp' and 'f5.si' domains are accesible, but it's hosted with DDNS, may blocked by some router or firewalls."
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
